### ISSUE TITLE
Running redund; Access is denied.

### ISSUE THREAD

**Issue by aragorn67** [SystemsBioinformatics/ecmtool#23]
Hi, i tried to test ecmtool with this command in the ecmtool folder, python main.py --model_path .\models\e_coli_core_rounded.xml,  get this error   File "C:\Users\a.antonakoudis\OneDrive - Sartorius Corporate Administration GmbH\Documents\Projects\Media Design\ecmtool\ecmtool\helpers.py", line 478, in redund
    raise ValueError('An error occurred during removal of redundant vectors from an input matrix: '
ValueError: An error occurred during removal of redundant vectors from an input matrix: redund did not write an output file after being presented input file "%s". Please check if your input matrix contains erroneous data, and let us know via https://github.com/SystemsBioinformatics/ecmtool/issues if you think the input matrix seems fine. It helps if you attach the matrix file mentioned above when creating an issue.

I've attached the tmp/matrix0.ine
[matrix0.txt](https://github.com/SystemsBioinformatics/ecmtool/files/11197617/matrix0.txt)

**Comment by tjclement** [comment]
Hi @aragorn67, thanks for reporting this. When we run the command you ran (`python main.py --model_path .\models\e_coli_core_rounded.xml`) on a freshly installed Windows machine, it completes without errors:

```
Enumerated 739 rays
Found 732 ECMs
Ran in 15.415319 seconds
```

Something you can check to debug this:
- Try downloading ecmtool to a local folder instead of your OneDrive. If that fixes the problem, ask your administrators to allow execution permissions on OneDrive, as ecmtool runs programs from there.

**Comment by aragorn67** [comment]
Thank you that was the problem!

**Comment by tjclement** [comment]
Glad to hear! We'd love to hear more from you if ecmtool proves useful to your work 👍
