### ISSUE TITLE
`get_conversion_cone()` function missing

### ISSUE THREAD

**Issue by hariszaf** [SystemsBioinformatics/ecmtool#25]
Hi! 
Thanks a lot for this amazing work of yours! 

I was wondering whether there's a mistake with your readme for the python library case.
You mention that "The most crucial method is ecmtool.conversion_cone:get_conversion_cone(), which returns the ECMs of a given stoichiometric matrix."

```from ecmtool.conversion_cone import get_conversion_cone```

but I could not find a `get_conversion_cone()` at all.

Am I missing something? 

Thanks a lot again!

**Comment by dhdegroot** [comment]
Hi @hariszaf,
That's a very good point. We inadvertently took this function out when we did a major update that made ecmtool more modular. This really benefits its speed and scaling on large models, but makes running it on small models a bit less transparent.
I'm currently restoring a version of get_conversion_cone, and will then update the readme. 

Thanks for your help in pointing this out. We will get back to you.

Best!

**Comment by hariszaf** [comment]
Hi @dhdegroot 

Thank you very much for your prompt reply, the amazing tool and the thorough explanation of its concepts!

Looking forward to it and please let me know if you think I could also be of help.

**Comment by dhdegroot** [comment]
Hi @hariszaf,
I just pushed an update in which I restored a get_conversion_cone()-function. This should work similarly to the old version, so I don't think I need to update the readme. Let me know if something is still non-functioning.
For your purposes, however, it's probably best to follow the workflow in main.py if you want to change the workings of ecmtool, since that has more of the options available than just using get_conversion_cone. You can always send us an email if you don't understand one of the steps in this main.py.

**Comment by hariszaf** [comment]
Hi @dhdegroot, 

thanks a lot for the guidance! 

Most likely I ll bother you again for the interpretation of the results. :sweat_smile:
